name: "Second_ParallelWorflow"
on: workflow_dispatch
jobs:
  FirstJob:
    runs-on: ubuntu-latest
    steps:
      - name: FirstStep
        run: echo "Welcome to Github actions workflow demo"
      - name: Second Step
        run: date
      - name: Third step
        run: ls
  SecondJob:
    runs-on: ubuntu-latest
    steps:
      - name: First Step in 2nd job
        run: |
          pwd
          echo uname -a > index.txt
          echo "Welcome to 2nd job"
  ThirdJob:
    runs-on: ubuntu-latest
    steps:
      - name: second step in 2nd job
        run: |
          date
          ls -l
          